---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-spot-handler
rules:
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - create
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-spot-handler
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-spot-handler
subjects:
- kind: ServiceAccount
  name: k8s-spot-handler
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-spot-handler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-spot-handler
  namespace: default
spec:
  selector:
    matchLabels:
      app: k8s-spot-handler
  template:
    metadata:
      labels:
        app: k8s-spot-handler
    spec:
      serviceAccountName: k8s-spot-handler
      containers:
      - name: k8s-spot-handler
        image: marcincuber/k8s-spot-handler:1.13.7-1
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SPOT_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: VERBOSE
          value: "0"
      nodeSelector:
        lifecycle: Ec2Spot # Ensure to have this node label available
